import type { Metadata } from "next";
import "../style/globals.css";
import localFont from "next/font/local";




export const metadata: Metadata = {
  title: "خودروی سورنا",
  description: "Generated by create next app",
};

const appFont = localFont({
  src: '../public/fonts/ttf/IRANSansWeb.ttf',
  // variable: '--font-iran-sans', // متغیر CSS برای فونت
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" >
      <body className={` antialiased relative w-full h-full ${appFont.className} sticky top-0`}>


   

        <div
          className="w-full min-h-52" >
          {children}
        </div>





      </body>
    </html >
  );
}
