import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/layout/Header/Header";
import Footer from "../components/layout/Foter/Footer";



export const metadata: Metadata = {
  title: "Dragon car shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={` antialiased relative w-full h-full`}>
        <Header />
        <div className=" pt-[80px] w-full h-screen" style={{ background: 'rgb(128, 139, 150 )' }}>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
