import type { Metadata } from "next";
import Navbar_components from "@/components/layout/navbar/Navbar";
import Footer from "@/components/layout/footer/Footer";
import LayoutContainer from "@/components/layout/layout/LayoutContainer";
import { MainContextProvider } from "@/context/MainContext";


export const metadata: Metadata = {
  title: "sorena",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <div>
      <Navbar_components></Navbar_components>
      {children}
      <Footer></Footer>
    </div>


  );
}
